import { NextRequest, NextResponse } from 'next/server'
import nodemailer from 'nodemailer'
import { renderToBuffer } from '@react-pdf/renderer'
import { buildProgramPDF } from '@/lib/pdf'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

function getTransporter() {
  const host = process.env.SMTP_HOST
  if (!host) return null

  return nodemailer.createTransport({
    host,
    port: parseInt(process.env.SMTP_PORT ?? '587', 10),
    secure: process.env.SMTP_SECURE === 'true',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  })
}

export async function POST(req: NextRequest): Promise<NextResponse> {
  let email: string
  let programText: string

  try {
    const body = await req.json()
    email = body.email
    programText = body.programText
  } catch {
    return NextResponse.json({ success: false, error: 'Invalid request body' }, { status: 400 })
  }

  if (!email || !programText) {
    return NextResponse.json({ success: false, error: 'Missing email or programText' }, { status: 400 })
  }

  console.log('[send-program] SMTP config check:', {
    SMTP_HOST: process.env.SMTP_HOST ?? '(not set)',
    SMTP_PORT: process.env.SMTP_PORT ?? '(not set)',
    SMTP_USER: process.env.SMTP_USER ?? '(not set)',
    SMTP_PASS: process.env.SMTP_PASS ? '(set)' : '(not set)',
    SMTP_FROM: process.env.SMTP_FROM ?? '(not set)',
  })

  const transporter = getTransporter()
  if (!transporter) {
    console.warn('[send-program] SMTP_HOST not set — email delivery disabled. Set SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM in your environment to enable.')
    return NextResponse.json({ success: false, error: 'Email delivery not configured' }, { status: 503 })
  }

  // Generate PDF
  let pdfBuffer: Buffer
  try {
    const element = buildProgramPDF(programText)
    pdfBuffer = await renderToBuffer(element)
  } catch (err) {
    console.error('[send-program] PDF generation failed:', err)
    return NextResponse.json({ success: false, error: 'PDF generation failed' }, { status: 500 })
  }

  // Send email
  try {
    const from = process.env.SMTP_FROM ?? process.env.SMTP_USER
    console.log(`[send-program] Attempting sendMail → to: ${email}, from: ${from}`)
    await transporter.sendMail({
      from,
      to: email,
      subject: 'Your Personalized Fitness Program — MyFitnessPlan',
      html: `
        <div style="font-family:sans-serif;max-width:600px;margin:0 auto;color:#222">
          <h2 style="color:#f97316">Your program is ready!</h2>
          <p>Your personalized 12-week fitness program is attached as a PDF.</p>
          <p>Open the attachment to view your full program — including your training phases, exercise selection, progression plan, and ${programText.includes('## NUTRITION') ? 'nutrition guidelines' : 'deload protocol'}.</p>
          <hr style="border:none;border-top:1px solid #eee;margin:24px 0"/>
          <p style="color:#999;font-size:12px">Generated by MyFitnessPlan. This program was built specifically for you — please don't share it.</p>
        </div>
      `,
      attachments: [
        {
          filename: 'my-fitness-program.pdf',
          content: pdfBuffer,
          contentType: 'application/pdf',
        },
      ],
    })

    console.log(`[send-program] Email sent to ${email}`)
    return NextResponse.json({ success: true })
  } catch (err) {
    console.error('[send-program] Email send failed:', err)
    return NextResponse.json({ success: false, error: 'Failed to send email' }, { status: 500 })
  }
}
