import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import { renderToBuffer } from '@react-pdf/renderer'
import { buildProgramPDF } from '@/lib/pdf'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

export async function POST(req: NextRequest): Promise<NextResponse> {
  let email: string
  let programText: string

  try {
    const body = await req.json()
    email = body.email
    programText = body.programText
  } catch {
    return NextResponse.json({ success: false, error: 'Invalid request body' }, { status: 400 })
  }

  if (!email || !programText) {
    return NextResponse.json({ success: false, error: 'Missing email or programText' }, { status: 400 })
  }

  const apiKey = process.env.RESEND_API_KEY
  console.log('[send-program] RESEND_API_KEY:', apiKey ? '(set)' : '(not set)')
  if (!apiKey) {
    console.warn('[send-program] RESEND_API_KEY not set — email delivery disabled.')
    return NextResponse.json({ success: false, error: 'Email delivery not configured' }, { status: 503 })
  }

  // Generate PDF
  let pdfBuffer: Buffer
  try {
    const element = buildProgramPDF(programText)
    pdfBuffer = await renderToBuffer(element)
  } catch (err) {
    console.error('[send-program] PDF generation failed:', err)
    return NextResponse.json({ success: false, error: 'PDF generation failed' }, { status: 500 })
  }

  // Send email
  try {
    const resend = new Resend(apiKey)
    console.log(`[send-program] Attempting send → to: ${email}, from: onboarding@resend.dev`)
    const { error } = await resend.emails.send({
      from: 'onboarding@resend.dev',
      to: email,
      subject: 'Your Personalized Fitness Program — MyFitnessPlan',
      html: `
        <div style="font-family:sans-serif;max-width:600px;margin:0 auto;color:#222">
          <h2 style="color:#f97316">Your program is ready!</h2>
          <p>Your personalized 12-week fitness program is attached as a PDF.</p>
          <p>Open the attachment to view your full program — including your training phases, exercise selection, progression plan, and ${programText.includes('## NUTRITION') ? 'nutrition guidelines' : 'deload protocol'}.</p>
          <hr style="border:none;border-top:1px solid #eee;margin:24px 0"/>
          <p style="color:#999;font-size:12px">Generated by MyFitnessPlan. This program was built specifically for you — please don't share it.</p>
        </div>
      `,
      attachments: [
        {
          filename: 'my-fitness-program.pdf',
          content: pdfBuffer.toString('base64'),
        },
      ],
    })

    if (error) {
      console.error('[send-program] Resend error:', error)
      return NextResponse.json({ success: false, error: 'Failed to send email' }, { status: 500 })
    }

    console.log(`[send-program] Email sent to ${email}`)
    return NextResponse.json({ success: true })
  } catch (err) {
    console.error('[send-program] Email send failed:', err)
    return NextResponse.json({ success: false, error: 'Failed to send email' }, { status: 500 })
  }
}
