import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

// react-pdf bundles Helvetica as a Latin-1 (ISO 8859-1) subset.
// Characters outside that range cause the layout engine to silently abort
// the text run, truncating everything that follows on the same page.
// Map the common offenders to safe ASCII equivalents before any text reaches <Text>.
function sanitize(text: string): string {
  return text
    .replace(/\u2014/g, '-')   // em dash  —
    .replace(/\u2013/g, '-')   // en dash  –
    .replace(/\u2192/g, '->')  // right arrow  →
    .replace(/\u2190/g, '<-')  // left arrow  ←
    .replace(/\u2265/g, '>=')  // greater-or-equal  ≥
    .replace(/\u2264/g, '<=')  // less-or-equal  ≤
    .replace(/\u00D7/g, 'x')   // multiplication sign  ×
    .replace(/\u2019/g, "'")   // right single quote  '
    .replace(/\u2018/g, "'")   // left single quote  '
    .replace(/\u201C/g, '"')   // left double quote  "
    .replace(/\u201D/g, '"')   // right double quote  "
    .replace(/\u2026/g, '...')  // ellipsis  …
}

const styles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 48,
    paddingHorizontal: 48,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
    color: '#1a1a1a',
  },
  title: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 4,
    color: '#111111',
  },
  subtitle: {
    fontSize: 10,
    color: '#888888',
    marginBottom: 20,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
    marginBottom: 14,
  },
  h2: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    marginTop: 16,
    marginBottom: 4,
    color: '#111111',
  },
  h3: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    marginTop: 10,
    marginBottom: 3,
    color: '#333333',
  },
  body: {
    fontSize: 9.5,
    lineHeight: 1.55,
    marginBottom: 1.5,
    color: '#333333',
  },
  spacer: { height: 5 },
  footer: {
    position: 'absolute',
    bottom: 28,
    left: 48,
    right: 48,
    textAlign: 'center',
    fontSize: 8,
    color: '#aaaaaa',
  },
})

// Plain builder function — not a React component.
// Returns a <Document> element whose type satisfies react-pdf's pdf() signature.
export function buildProgramPDF(programText: string) {
  const lines = programText.split('\n')

  return (
    <Document
      title="My Personalized Fitness Program"
      author="MyFitnessPlan"
      creator="MyFitnessPlan"
    >
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>My Personalized Fitness Program</Text>
        <Text style={styles.subtitle}>Generated by MyFitnessPlan - myfitnesplan.com</Text>
        <View style={styles.divider} />

        {lines.map((line, i) => {
          if (line.startsWith('## ')) {
            return <Text key={i} style={styles.h2}>{sanitize(line.slice(3).trim())}</Text>
          }
          if (line.startsWith('### ')) {
            return <Text key={i} style={styles.h3}>{sanitize(line.slice(4).trim())}</Text>
          }
          if (line.trim() === '' || line.trim() === '---') {
            return <View key={i} style={styles.spacer} />
          }
          // Strip bold markers then sanitize
          const cleaned = sanitize(line.replace(/\*\*(.*?)\*\*/g, '$1'))
          return <Text key={i} style={styles.body}>{cleaned}</Text>
        })}

        <Text style={styles.footer} fixed>
          MyFitnessPlan - Your program is personal - do not redistribute
        </Text>
      </Page>
    </Document>
  )
}
